# Jekyll configuration

name: Blog Name
description: >
  This is a description of this awsome webpage/blog.
  It is really just an example to show what this jekyll theme looks like.

# Url for domain, example: www.example.com
url: https://lentzi90.github.io

# Is this site served at the root of the domain or in some project folder?
# Example: www.example.com/blog -> baseurl: blog
baseurl: '/jekyll-dark-orange'

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: lentzi90
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus:
comments: false

permalink: /:year/:month/:title.html

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE', 'TODO.md', 'serve.sh']
